;; Explicit domains and registry-identity snapshot controls; no timing oracle.
(import (chezscheme))
(load "host/chez/rt.ss")
(define total 0)
(define fails 0)
(define (ok name value)
  (set! total (+ total 1))
  (unless value (set! fails (+ fails 1)) (printf "FAIL: ~a\n" name)))
(define (isolated thunk)
  (let ((arms jolt-eq-arms))
    (dynamic-wind (lambda () (set! jolt-eq-arms '())) thunk
      (lambda () (set! jolt-eq-arms arms)))))

(isolated (lambda ()
  (let ((calls 0) (handler-calls 0))
    (register-value-eq-arm!
      (lambda (a b) (set! calls (+ calls 1)) (or (htable? a) (htable? b)))
      (lambda (a b) (set! handler-calls (+ handler-calls 1)) #t))
    (ok "runtime-owned collection probes still validate domain predicates" (> calls 0))
    (set! calls 0)
    (ok "registered domain arm retained in full registry" (= 1 (length jolt-eq-arms)))
    (ok "filtered snapshot truly omits opted-in arm" (null? (eq-scalar-arms jolt-eq-arms)))
    (ok "procedure/string stays false" (not (jolt=2 car "x")))
    (ok "reverse mixed pair stays false" (not (jolt=2 "x" car)))
    (ok "nil fast path remains false" (not (jolt=2 car jolt-nil)))
    (ok "out-of-domain callbacks absent" (and (= calls 0) (= handler-calls 0)))
    (let ((obj (jolt-tagged-table (keyword "snapshot" "test"))))
      (ok "native-value/procedure pair invokes arm" (jolt=2 obj car))
      (ok "procedure/native-value pair invokes arm" (jolt=2 car obj))
      (ok "both in-domain callbacks preserved" (and (= calls 2) (= handler-calls 2)))))))

(isolated (lambda ()
  (let ((trace '()))
    (define (mixed a b) (and (procedure? a) (string? b)))
    (register-eq-arm! mixed (lambda (a b) (set! trace (cons 'old-handler trace)) #t))
    (let ((older jolt-eq-arms))
      (register-value-eq-arm! (lambda (a b) (error 'test "domain leaked")) mixed)
      (register-eq-arm!
        (lambda (a b) (set! trace (cons 'new-pred trace)) #f) mixed)
      (set! trace '())
      (ok "legacy mixed handler still wins" (jolt=2 car "x"))
      (ok "legacy predicate order/effects unchanged"
          (equal? '(new-pred old-handler) (reverse trace)))
      (let ((newer jolt-eq-arms))
        (ok "snapshot is reused for unchanged registry"
            (eq? (eq-scalar-arms newer) (eq-scalar-arms newer)))
        (set! jolt-eq-arms older)
        (set! trace '())
        (ok "direct restore invalidates newer snapshot" (jolt=2 car "x"))
        (ok "restored registry excludes newer callbacks" (equal? '(old-handler) (reverse trace)))
        (set! jolt-eq-arms newer)
        (set! trace '())
        (ok "restoring newer registry works again" (jolt=2 car "x"))
        (ok "restored newer callback order" (equal? '(new-pred old-handler) (reverse trace))))))))

(isolated (lambda ()
  (let ((armed #f) (trace '()))
    (register-eq-arm! (lambda (a b) (and (procedure? a) (string? b)))
      (lambda (a b) (set! trace (cons 'old trace)) #t))
    (register-eq-arm!
      (lambda (a b)
        (when armed
          (set! armed #f)
          (register-eq-arm! (lambda (x y) (and (procedure? x) (string? y)))
            (lambda (x y) (set! trace (cons 'new trace)) #f)))
        #f) (lambda (a b) #f))
    (set! armed #t)
    (ok "registration during walk does not change captured list" (jolt=2 car "x"))
    (ok "captured old handler observed" (equal? '(old) trace))
    (set! trace '())
    (ok "next comparison sees newly registered handler" (not (jolt=2 car "x")))
    (ok "new handler observed" (equal? '(new) trace)))))

(isolated (lambda ()
  (let ((calls 0) (before jolt-eq-arms))
    (ok "invalid domain throws before callbacks or mutation"
      (guard (e (#t (and (= calls 0) (eq? before jolt-eq-arms))))
        (register-eq-arm! (lambda (a b) (set! calls (+ calls 1)) #f)
                         (lambda (a b) #f) 'unknown)
        #f))
    (register-eq-arm!
      (lambda (a b) (if (and (procedure? a) (string? b))
                       (error 'test "legacy-error") #f))
      (lambda (a b) #f))
    (ok "legacy throwing predicate is not skipped"
      (guard (e (#t #t)) (jolt=2 car "x") #f)))))
;; A constructor procedure is equal to its native Class representation. It is
;; deliberately NOT a procedure/scalar pair and must retain native arms.
(let ((ctor (lambda () 'unused)) (name "snapshot.MixedConstructor"))
  (deftype-ctor-tag-set! ctor name)
  (let ((class (jolt-class-for name)))
    (ok "constructor/native Class equality retained" (jolt=2 ctor class))
    (ok "native Class/constructor equality retained" (jolt=2 class ctor))))
(isolated (lambda ()
  (let ((before jolt-eq-arms) (calls 0))
    (define (numbers a b) (set! calls (+ calls 1)) (and (number? a) (number? b)))
    (ok "legacy raw scalar claim is rejected"
      (guard (e (#t (eq? before jolt-eq-arms)))
        (register-eq-arm! numbers (lambda (a b) #t)) #f))
    (set! calls 0)
    ;; An explicit domain restricts the effective predicate. Validating its
    ;; raw callback would violate the opted-in no-callback-outside-domain rule.
    (register-value-eq-arm! numbers (lambda (a b) #t))
    (ok "effective native domain suppresses raw scalar registration probes" (= calls 3))
    (set! calls 0)
    (ok "restricted raw scalar claim cannot change numeric equality" (not (jolt=2 1 2)))
    (ok "numeric fast route invokes no restricted callbacks" (= calls 0))
    (let ((before jolt-eq-arms))
      (ok "effective domain still rejects runtime-owned collection claims"
        (guard (e (#t (eq? before jolt-eq-arms)))
          (register-value-eq-arm! (lambda (a b) (and (pvec? a) (pvec? b)))
                                 (lambda (a b) #t)) #f))))))
(printf "equality-domain-snapshot: ~a/~a passed\n" (- total fails) total)
(exit (if (zero? fails) 0 1))
