;; Source semantics and non-vacuity gate; run from the repository root.
(import (chezscheme))
(load "host/chez/rt.ss")
(define total 0)
(define fails 0)
(define (ok label value)
  (set! total (+ total 1))
  (unless value (set! fails (+ fails 1)) (printf "FAIL: ~a\n" label)))
(define (answer n) (lambda (obj) n))
(define old (answer 1))
(define new (answer 2))
(define other (answer 3))
(define proto "string.site/Methods")
(register-protocol-method "Object" proto "m" old)
(register-protocol-method "string.site.Other" proto "m" other)
(define register-class (var-deref "clojure.core" "__register-class!"))
(define (isolated thunk)
  (let ((arms jt-user-value-tags-arms) (domains jt-user-value-tags-domain-snapshot)
        (classes jolt-class-arms) (tags value-host-tags))
    (dynamic-wind
      (lambda () (set! jt-user-value-tags-arms '())
                 (set! jt-user-value-tags-domain-snapshot #f))
      thunk
      (lambda () (set! jt-user-value-tags-arms arms)
                 (set! jt-user-value-tags-domain-snapshot domains)
                 (set! jolt-class-arms classes) (set! value-host-tags tags)))))
(define (enable-domain)
  (register-class (lambda (x) #f) (lambda (x) "string.site.Never")
                  (lambda (x) empty-pvec) (keyword #f "host-table")))

(isolated (lambda ()
  (enable-domain)
  (let ((s (make-protocol-method-site proto "m"))
        (original jch-tags) (calls 0))
    (ok "runtime tag-chain ownership is explicit"
      (and (top-level-bound? 'protocol-string-tag-chain-owner)
           (eq? value-host-tags (top-level-value 'protocol-string-tag-chain-owner))))
    (dynamic-wind
      (lambda () (set! jch-tags (lambda (name)
        (set! calls (+ calls 1)) (original name))))
      (lambda ()
        (ok "cold method matches ordinary resolution" (eq? old (s "cold")))
        (ok "cold lookup reaches actual tag production" (> calls 0))
        (set! calls 0)
        (do ((i 0 (+ i 1))) ((= i 20))
          (ok "warm string family method" (eq? old (s "warm"))))
        (ok "warm owned domain omits tag production" (= calls 0))
        (register-protocol-method "java.lang.String" proto "m" new)
        (ok "completed protocol extension invalidates family cache" (eq? new (s "changed")))
        (ok "protocol invalidation reclassifies" (> calls 0))
        (set! calls 0)
        (jch-set-supers! "string.site.Unrelated" '("Object"))
        (ok "completed graph update keeps actual method" (eq? new (s "graph")))
        (ok "graph invalidation reclassifies" (> calls 0)))
      (lambda () (set! jch-tags original)))
    (register-protocol-method "java.lang.String" proto "m" old)
    (s "warm")
    (let ((snapshot jt-user-value-tags-domain-snapshot) (effects 0))
      (register-class (lambda (x) (when (string? x) (set! effects (+ effects 1))) #f)
                      (lambda (x) "string.site.Legacy") (lambda (x) empty-pvec))
      (set! effects 0)
      (ok "legacy registration keeps result" (eq? old (s "legacy")))
      (ok "legacy predicate still runs once" (= effects 1))
      ;; Publication gap: a previous all-domain summary is not current proof.
      (set! jt-user-value-tags-domain-snapshot snapshot)
      (set! effects 0)
      (s "stale") (s "stale")
      (ok "stale summary cannot suppress legacy predicate" (= effects 2))))))

(isolated (lambda ()
  (enable-domain)
  (let ((s (make-protocol-method-site proto "m"))
        (original value-host-tags) (effects 0))
    (s "warm")
    (dynamic-wind
      (lambda () (set! value-host-tags (lambda (x)
        (when (string? x) (set! effects (+ effects 1)))
        (jch-tags "string.site.Other"))))
      (lambda ()
        (ok "unknown chain changes actual receiver classification" (eq? other (s "changed")))
        (ok "unknown chain is not cached after its first call" (eq? other (s "changed")))
        (ok "unknown chain effects remain per call" (= effects 2))
        (let ((fresh (make-protocol-method-site proto "m")))
          (fresh "new") (fresh "new")
          (ok "factory never captures arbitrary current chain as pure" (= effects 4))))
      (lambda () (set! value-host-tags original))))))

;; Shared immutable family snapshots: stable epoch, several real Scheme threads.
(isolated (lambda ()
  (enable-domain)
  (let ((s (make-protocol-method-site proto "m"))
        (mu (make-mutex)) (done 0) (errors 0))
    (do ((worker 0 (+ worker 1))) ((= worker 4))
      (fork-thread (lambda ()
        (guard (e (#t (with-mutex mu (set! errors (+ errors 1)))))
          (do ((i 0 (+ i 1))) ((= i 200))
            (for-each (lambda (x)
              (unless (eq? old (s x)) (error 'string-site "wrong immutable snapshot")))
              (list "shared" 7 empty-pmap (jolt-vector 1)))))
        (with-mutex mu (set! done (+ done 1))))))
    (let wait () (unless (with-mutex mu (= done 4)) (sleep (make-time 'time-duration 1000000 0)) (wait)))
    (ok "concurrent family publication preserves selection" (= errors 0)))))

(printf "protocol-string-family-site: ~a/~a checks passed\n" (- total fails) total)
(exit (if (= fails 0) 0 1))
