;; Source gate for the core-owned host protocol site. No compiler build needed.
(import (chezscheme))
(load "host/chez/rt.ss")
;; Optional causal control: exact original per-call resolver, no cache. This
;; same script can run from the untouched parent without the new helper bound.
(define make-site
  (if (equal? (getenv "PROTOCOL_SITE_CONTROL") "uncached")
      (lambda (proto method) (lambda (obj) (protocol-resolve proto method obj)))
      (top-level-value 'make-protocol-method-site)))
(define total 0)
(define fails 0)
(define (ok name pred)
  (set! total (+ total 1))
  (unless pred (set! fails (+ fails 1)) (printf "FAIL: ~a\n" name)))
(define (thrown thunk) (guard (e (#t e)) (thunk) #f))
(define (answer n) (lambda (obj) n))
(define proto "site/Methods")
(define old (answer 1))
(define new (answer 2))
(define other (answer 3))
(register-protocol-method "Object" proto "m" old)
(register-protocol-method "nil" proto "m" old)
(define site (make-site proto "m"))
(define test-values (list "s" 7 1.5 #t #\a empty-pmap (jolt-vector 1)
                     (keyword #f "k") (jolt-symbol #f "s") jolt-nil))
(for-each (lambda (x)
  (ok "built-in selection matches uncached resolver"
      (eq? (site x) (protocol-resolve proto "m" x)))) test-values)

;; Actual cold probes are positive; warmed strings retain tag effects but remove
;; registry probes. Never invoke the selected method while the lock is held.
(let ((resolve find-protocol-method) (tags value-host-tags)
      (probes 0) (tag-calls 0) (tag-locks '())
      (fresh (make-site proto "m")))
  (dynamic-wind
    (lambda ()
      (set! find-protocol-method (lambda args
        (set! probes (+ probes 1)) (apply resolve args)))
      (set! value-host-tags (lambda (x)
        (set! tag-calls (+ tag-calls 1))
        (set! tag-locks (cons (jolt-locks-held) tag-locks)) (tags x))))
    (lambda ()
      (fresh "cold")
      (ok "cold lookup really walks registry" (> probes 0))
      (set! probes 0)
      (do ((i 0 (+ i 1))) ((= i 10)) (ok "warm result" (eq? old (fresh "warm"))))
      (ok "warm lookup removes registry walk" (= probes 0))
      (ok "tag producer runs once on every cold/hot call" (= tag-calls 11))
      (ok "tag producer never runs under a counted lock" (for-all zero? tag-locks)))
    (lambda () (set! find-protocol-method resolve) (set! value-host-tags tags))))
(register-protocol-method "java.lang.String" proto "m" new)
(ok "completed extension invalidates warm method" (eq? new (site "s")))
(register-protocol-method "java.lang.String" proto "m" other)
(ok "re-extension selects newest method" (eq? other (site "s")))
(register-protocol-method "java.lang.String" "site/Other" "m" old)
(register-protocol-method "java.lang.String" proto "other" new)
(ok "protocol identity is site-local" (eq? old ((make-site "site/Other" "m") "s")))
(ok "method identity is site-local" (eq? new ((make-site proto "other") "s")))
(let ((missing (make-site "site/Missing" "m")))
  (ok "missing implementation still throws" (thrown (lambda () (missing "s"))))
  (register-protocol-method "Object" "site/Missing" "m" new)
  (ok "a missing result was not cached" (eq? new (missing "s"))))

;; User tag predicates retain order, effects, dynamic choices, errors and live
;; registrations. Their freshly converted lists must not alias built-in entries.
(let ((arms jt-user-value-tags-arms) (trace '()) (choice "site/UserA")
      (obj (vector 'site-extension))
      (reg (var-deref "clojure.core" "__register-class!")))
  (register-protocol-method "site/UserA" proto "m" old)
  (register-protocol-method "site/UserB" proto "m" new)
  (dynamic-wind
    (lambda ()
      (set! jt-user-value-tags-arms '())
      (ok "extension value initially uses Object method" (eq? old (site obj)))
      (reg (lambda (x) (set! trace (cons 'first trace)) #f)
           (lambda (x) "unused") (lambda (x) (jolt-vector "unused")))
      (reg (lambda (x) (set! trace (cons 'second trace)) (eq? x obj))
           (lambda (x) choice)
           (lambda (x) (set! trace (cons 'tags trace)) (jolt-vector choice)))
      (set! trace '()))
    (lambda ()
      (ok "new user registration overrides a previously warmed Object method" (eq? old (site obj)))
      (set! choice "site/UserB")
      (ok "user tag results remain live" (eq? new (site obj)))
      (ok "predicate and tag effects retain order on both calls"
          (equal? '(first second tags first second tags) (reverse trace)))
      (set! jt-user-value-tags-arms (list (cons (lambda (x) (error 'site-test "predicate")) (lambda (x) '()))))
      (ok "predicate exception not skipped by warm cache" (thrown (lambda () (site obj)))))
    (lambda () (set! jt-user-value-tags-arms arms))))

(let ((arms jt-user-value-tags-arms) (calls 0) (unlocked? #t))
  (dynamic-wind
    (lambda () (set! jt-user-value-tags-arms
      (list (cons (lambda (x)
                    (set! calls (+ calls 1))
                    (set! unlocked? (and unlocked? (= 0 (jolt-locks-held))))
                    (register-protocol-method "java.lang.String" proto "m" new)
                    #f)
                  (lambda (x) '())))))
    (lambda ()
      (ok "predicate registration is visible to the same dispatch" (eq? new (site "s")))
      (ok "registering predicate is called exactly once outside lock" (and (= calls 1) unlocked?)))
    (lambda () (set! jt-user-value-tags-arms arms))))

;; Record/reify precedence and instance-local method mutation delegate unchanged.
(let* ((desc (make-jrdesc "site.Record" '()))
       (obj (make-jrec desc (vector) jolt-nil))
       (empty-r (make-reified (jolt-hash-map)))
       (r (make-reified (jolt-hash-map "m" old)))
       (methods (cdr (jreify-methods r))))
  (register-protocol-method "site.Record" proto "m" new)
  (ok "record dispatch delegates" (eq? (site obj) (protocol-resolve proto "m" obj)))
  (ok "reify fallback delegates" (eq? (site empty-r) (protocol-resolve proto "m" empty-r)))
  (vector-set! methods 0 other)
  (ok "reify instance method precedes extensions" (eq? other (site r)))
  (vector-set! methods 0 new)
  (ok "reify instance method mutation stays live" (eq? new (site r))))
(let ((m (jolt-with-meta empty-pmap (pmap-assoc empty-pmap (keyword #f "m") new))))
  (ok "metadata keeps existing ordinary resolver semantics"
      (eq? (site m) (protocol-resolve proto "m" m))))

;; Raw test tag producer returns actual graph-owned lists. Mutating the graph
;; after producing tags must not stamp the OLD list with the NEW graph epoch.
(let ((tags value-host-tags) (change? #f) (calls 0))
  (jch-set-supers! "site.Graph" '("site.ParentA"))
  (register-protocol-method "site.ParentA" proto "m" old)
  (register-protocol-method "site.ParentB" proto "m" new)
  (dynamic-wind
    (lambda () (set! value-host-tags (lambda (x)
      (set! calls (+ calls 1))
      (let ((ts (jch-tags "site.Graph")))
        (when change? (set! change? #f) (jch-set-supers! "site.Graph" '("site.ParentB")))
        ts))))
    (lambda ()
      (let ((s (make-site proto "m")))
        (ok "initial graph method" (eq? old (s "x")))
        (set! change? #t)
        (ok "overlapping graph change preserves this call's actual tags" (eq? old (s "x")))
        (ok "completed graph change selects new ancestry" (eq? new (s "x")))
        (ok "graph change does not rerun user tag production" (= calls 3))))
    (lambda () (set! value-host-tags tags))))

;; Bounded cache: nine graph-owned classes evict an old entry, not semantics.
(let ((tags value-host-tags) (resolve find-protocol-method) (probes 0))
  (do ((i 0 (+ i 1))) ((= i 9))
    (jch-set-supers! (string-append "site.Bounded" (number->string i)) '()))
  (dynamic-wind
    (lambda ()
      (set! value-host-tags (lambda (x) (jch-tags x)))
      (set! find-protocol-method (lambda args (set! probes (+ probes 1)) (apply resolve args))))
    (lambda ()
      (let ((s (make-site proto "m")))
        (do ((i 0 (+ i 1))) ((= i 9))
          (ok "bounded site resolves all classes" (eq? old (s (string-append "site.Bounded" (number->string i))))))
        (set! probes 0)
        (s "site.Bounded8")
        (ok "newest bounded entry hits" (= probes 0))
        (s "site.Bounded0")
        (ok "oldest entry was evicted and re-resolved" (> probes 0))))
    (lambda () (set! value-host-tags tags) (set! find-protocol-method resolve))))

;; Prune callbacks can fill a site immediately before their deletion. Preserve
;; three traversal phases, callback lock visibility, and deletion-before-next-use.
(let ((tags value-host-tags) (removed-calls 0) (kept-calls 0) (locks '())
      (s (make-site proto "m")))
  (jch-set-supers! "site.Prune" '())
  (register-protocol-method "site.Prune" proto "m" new)
  (register-protocol-method "site.Keep" proto "m" other)
  (hashtable-set! type-class-memo "site.Prune" #t)
  (hashtable-set! type-class-memo "site.Keep" #t)
  (dynamic-wind
    (lambda () (set! value-host-tags (lambda (x) (jch-tags "site.Prune"))))
    (lambda ()
      (prune-type-registry! (lambda (tag)
        (set! locks (cons (jolt-locks-held) locks))
        (when (string=? tag "site.Keep") (set! kept-calls (+ kept-calls 1)))
        (if (string=? tag "site.Prune")
            (begin
              (set! removed-calls (+ removed-calls 1))
              (ok "prune callback sees preceding mutations"
                  (eq? (s "x") (if (= removed-calls 1) new old)))
              #f)
            #t)))
      (ok "prune callback populated entry does not survive deletion" (eq? old (s "x")))
      (ok "kept key retains all three callback phases" (= kept-calls 3))
      (ok "first-phase removal remains absent in second phase" (= removed-calls 2))
      (ok "keep? never runs under a counted lock" (for-all zero? locks)))
    (lambda () (set! value-host-tags tags))))
(forget-type-methods! "java.lang.String")
(ok "forget invalidates warm built-in entry" (eq? old (site "s")))

;; Bounded OS-thread coordination. No scheduler/fiber callbacks occur in the
;; production lock. Test-only interposition pauses a cold registry read while a
;; real register-protocol-method overlaps it; the miss MUST hold rec-tbl-mu.
(define (seconds-now)
  (let ((t (current-time 'time-monotonic)))
    (+ (time-second t) (/ (time-nanosecond t) 1000000000.0))))
(define (await pred)
  (let ((deadline (+ (seconds-now) 10)))
    (let loop ()
      (cond ((pred) #t) ((> (seconds-now) deadline) (error 'site-test "thread deadline"))
            (else (sleep (make-time 'time-duration 1000000 0)) (loop))))))
(let ((resolve find-protocol-method) (mu (make-mutex))
      (entered #f) (release #f) (attempted #f) (done 0) (errors 0)
      (locked? #f) (selected #f) (s (make-site "site/Race" "m")))
  (define (read-state pred) (with-mutex mu (pred)))
  (define (finish thunk)
    (guard (e (#t (with-mutex mu (set! errors (+ errors 1))))) (thunk))
    (with-mutex mu (set! done (+ done 1))))
  (register-protocol-method "java.lang.String" "site/Race" "m" old)
  (dynamic-wind
    (lambda () (set! find-protocol-method (lambda (tag pn mn)
      (let ((f (resolve tag pn mn)))
        (when (and f (string=? pn "site/Race") (read-state (lambda () (not entered))))
          (with-mutex mu (set! locked? (> (jolt-locks-held) 0)) (set! entered #t))
          (await (lambda () (read-state (lambda () release)))))
        f))))
    (lambda ()
      (fork-thread (lambda () (finish (lambda () (set! selected (s "x"))))))
      (await (lambda () (read-state (lambda () entered))))
      (fork-thread (lambda () (finish (lambda ()
        (with-mutex mu (set! attempted #t))
        (register-protocol-method "java.lang.String" "site/Race" "m" new)))))
      (await (lambda () (read-state (lambda () attempted))))
      (with-mutex mu (set! release #t))
      (await (lambda () (read-state (lambda () (= done 2)))))
      (ok "cold fill is inside registry lock" locked?)
      (ok "overlapping resolver selected original method" (eq? old selected))
      (ok "overlap threads finished without errors" (= errors 0))
      (ok "completed concurrent registration cannot leave a stale fill" (eq? new (s "x"))))
    (lambda () (set! find-protocol-method resolve))))

;; Concurrent first fills/hits see only whole initialized snapshots.
(let ((mu (make-mutex)) (done 0) (errors 0) (s (make-site proto "m")))
  (do ((thread 0 (+ thread 1))) ((= thread 4))
    (fork-thread (lambda ()
      (guard (e (#t (with-mutex mu (set! errors (+ errors 1)))))
        (do ((i 0 (+ i 1))) ((= i 100))
          (for-each (lambda (x) (unless (eq? old (s x)) (error 'site-test "wrong snapshot"))) test-values)))
      (with-mutex mu (set! done (+ done 1))))))
  (await (lambda () (with-mutex mu (= done 4))))
  (ok "concurrent bounded snapshots preserve method selection" (= errors 0)))

(printf "protocol-method-site: ~a/~a checks passed\n" (- total fails) total)
(unless (= fails 0) (exit 1))
