(import (chezscheme))
(load "host/chez/rt.ss")
(define total 0)
(define fails 0)
(define (ok label value)
  (set! total (+ total 1))
  (unless value (set! fails (+ fails 1)) (printf "FAIL: ~a\n" label)))
(define proto "primitive.site/Methods")
(define ordinary (lambda (x) 0))
(define changed (lambda (x) 1))
(register-protocol-method "Object" proto "m" ordinary)
(register-protocol-method "nil" proto "m" ordinary)
(define register-class (var-deref "clojure.core" "__register-class!"))
(register-class (lambda (x) #f) (lambda (x) "primitive.site.Never")
                (lambda (x) empty-pvec) (keyword #f "host-table"))
(ok "primitive tag ownership is separately explicit"
    (eq? value-host-tags protocol-primitive-tag-chain-owner))
(define hashmap
  (let loop ((i 0) (m empty-pmap))
    (if (= i 20) m (loop (+ i 1) (pmap-assoc m i i)))))
(define families (list "s" 7 9223372036854775808 1.5 #t jolt-nil
                       (keyword #f "k") (jolt-vector 1) empty-pmap hashmap))
(ok "hash map fixture really has distinct representation" (not (pmap-array? hashmap)))
(ok "family keys keep long and bigint distinct"
    (not (= (protocol-method-family 9223372036854775807)
            (protocol-method-family 9223372036854775808))))
(ok "map entry is not a plain vector family" (not (protocol-method-family (make-map-entry 1 2))))
(ok "subvec is not a plain vector family" (not (protocol-method-family (pvec-as-subvec (jolt-vector 1 2)))))
(define site (make-protocol-method-site proto "m"))
(let ((original jch-tags) (calls 0))
  (dynamic-wind
    (lambda () (set! jch-tags (lambda (name) (set! calls (+ calls 1)) (original name))))
    (lambda ()
      (for-each (lambda (x) (ok "cold selection is exact" (eq? (site x) (protocol-resolve proto "m" x)))) families)
      (ok "cold paths reach actual classification" (> calls 0))
      (set! calls 0)
      (do ((i 0 (+ i 1))) ((= i 3))
        (for-each (lambda (x) (ok "warm family result" (eq? ordinary (site x)))) families))
      (ok "warm families avoid tag production" (= calls 0))
      (register-protocol-method "java.lang.Boolean" proto "m" changed)
      (ok "boolean extension invalidates" (eq? changed (site #f)))
      (ok "boolean remains its own family" (eq? ordinary (site 7)))
      (register-protocol-method "java.lang.Long" proto "m" changed)
      (ok "long maximum is in long family" (eq? changed (site 9223372036854775807)))
      (ok "wide bigint is not long family" (eq? ordinary (site 9223372036854775808)))
      (register-protocol-method "clojure.lang.PersistentArrayMap" proto "m" changed)
      (ok "array-map extension invalidates its family" (eq? changed (site empty-pmap)))
      (ok "hash map does not inherit array-map method" (eq? ordinary (site hashmap)))
      (register-protocol-method "clojure.lang.PersistentVector" proto "m" changed)
      (ok "plain vector sees completed extension" (eq? changed (site (jolt-vector 1))))
      (ok "map entry retains ordinary concrete dispatch" (eq? (site (make-map-entry 1 2)) (protocol-resolve proto "m" (make-map-entry 1 2))))
      (ok "subvec retains ordinary concrete dispatch" (eq? (site (pvec-as-subvec (jolt-vector 1 2))) (protocol-resolve proto "m" (pvec-as-subvec (jolt-vector 1 2)))))
      (site 1.5) (set! calls 0)
      (jch-set-supers! "primitive.site.Unrelated" '("Object"))
      (ok "graph update preserves actual method" (eq? ordinary (site 1.5)))
      (ok "graph update reclassifies" (> calls 0)))
    (lambda () (set! jch-tags original))))
(register-protocol-method "java.lang.Boolean" proto "m" ordinary)
(register-protocol-method "java.lang.Long" proto "m" ordinary)
(register-protocol-method "clojure.lang.PersistentVector" proto "m" ordinary)
(register-protocol-method "clojure.lang.PersistentArrayMap" proto "m" ordinary)

(let ((arms jt-user-value-tags-arms) (snapshot jt-user-value-tags-domain-snapshot) (effects 0))
  (site #t)
  (dynamic-wind
    (lambda () (register-class (lambda (x) (when (boolean? x) (set! effects (+ effects 1))) #f)
                              (lambda (x) "primitive.site.Legacy") (lambda (x) empty-pvec)))
    (lambda ()
      (set! effects 0) (site #t) (site #f)
      (ok "legacy predicates execute per value" (= effects 2))
      (set! jt-user-value-tags-domain-snapshot snapshot)
      (set! effects 0) (site #t) (site #f)
      (ok "stale domain cannot suppress callbacks" (= effects 2)))
    (lambda () (set! jt-user-value-tags-arms arms)
               (set! jt-user-value-tags-domain-snapshot snapshot))))
(let ((tags value-host-tags) (effects 0))
  (site #t)
  (dynamic-wind
    (lambda () (set! value-host-tags (lambda (x)
                  (when (boolean? x) (set! effects (+ effects 1))) (tags x))))
    (lambda ()
      (site #t) (site #f)
      (ok "unknown replacement chain effects remain live" (= effects 2))
      (let ((fresh (make-protocol-method-site proto "m")))
        (fresh #t) (fresh #f)
        (ok "factory cannot confer ownership on unknown chain" (= effects 4))))
    (lambda () (set! value-host-tags tags))))

(let ((shared (make-protocol-method-site proto "m"))
      (mu (make-mutex)) (done 0) (errors 0))
  (do ((worker 0 (+ worker 1))) ((= worker 4))
    (fork-thread (lambda ()
      (guard (e (#t (with-mutex mu (set! errors (+ errors 1)))))
        (do ((i 0 (+ i 1))) ((= i 200))
          (for-each (lambda (x) (unless (eq? ordinary (shared x))
                                 (error 'primitive-site "wrong published method"))) families)))
      (with-mutex mu (set! done (+ done 1))))))
  (let wait () (unless (with-mutex mu (= done 4))
                (sleep (make-time 'time-duration 1000000 0)) (wait)))
  (ok "concurrent multi-family publication remains coherent" (= errors 0)))
(printf "protocol-primitive-family-site: ~a/~a checks passed\n" (- total fails) total)
(exit (if (= fails 0) 0 1))
