(import (chezscheme))
(load "host/chez/rt.ss")
(define total 0)
(define failures 0)
(define (check label pred)
  (set! total (+ total 1))
  (unless pred (set! failures (+ failures 1)) (printf "FAIL ~a\n" label)))
(define (expanded? source)
  (let-values (((sre opts) (java-pattern->sre source)))
    (let-values (((expanded changed?) (regex-static-repeats sre))) changed?)))
(check "digest class expanded" (expanded? "[0-9a-f]{64}"))
(check "single-character repeat expanded" (expanded? "a{8}"))
(check "variable repeat unchanged" (not (expanded? "[a-f]{1,8}")))
(check "lazy repeat unchanged" (not (expanded? "[a-f]{8}?")))
(check "captured body not duplicated" (not (expanded? "(a){8}")))
(check "large repeat unchanged" (not (expanded? "a{129}")))
(check "nested compound unchanged" (not (expanded? "(?:ab){8}")))
(check "zero repeat unchanged" (not (expanded? "a{0}")))
(check "expansion budget prevents unbounded copies"
  (let-values (((result changed?)
                (regex-static-repeats
                  (cons 'seq (make-list 100 '(** 128 128 #\a))))))
    (and changed? (= (length (filter (lambda (x) (eq? (car x) 'seq))
                                   (cdr result))) 32))))
(define (answer matcher text)
  (let ((m (matcher text))) (if m (jolt-str (irx-result m)) "nil")))
(define texts
  (append '("" "a" "aa" "aaa" "aaaa" "aaaaa" "ab" "aaaaaaab" "xxaaaaaay"
            "ababab" "ABCDEF" "abcxyz" "éé" "aaaa\n")
          (map (lambda (n) (make-string n #\a)) '(7 8 9 31 32 33 63 64 65))))
(for-each
 (lambda (source)
   (let-values (((sre opts) (java-pattern->sre source)))
     (let ((old (apply irregex sre 'backtrack opts))
           (new (regex-t-irx (jolt-regex source))))
       (for-each
        (lambda (text)
          (check "whole match agrees with original backtracker"
                 (equal? (answer (lambda (s) (irregex-match old s)) text)
                         (answer (lambda (s) (irregex-match new s)) text)))
          (check "search/captures agree with original backtracker"
                 (equal? (answer (lambda (s) (irregex-search old s)) text)
                         (answer (lambda (s) (irregex-search new s)) text)))) texts))))
 '("[0-9a-f]{64}" "a{8}" "a{1}|aa" "(?:a{2}|a{3})" "(a{2})b"
   "(?i)[a-f]{8}" "(?<token>[a-f]{8})" "(a){8}" "[a-f]{1,8}"
   "[a-f]{8}?" "[a-f]{8}+" "[a-f]{8}$" "a{129}" "a{0}"))
(let-values (((sre opts) (java-pattern->sre "[0-9a-f]{64}")))
  (let ((old (apply irregex sre 'backtrack opts))
        (new (regex-t-irx (jolt-regex "[0-9a-f]{64}")))
        (text (make-string 64 #\a)))
    (define (allocated irx)
      (irregex-match irx text)
      (let ((before (sstats-bytes (statistics))))
        (do ((i 0 (+ i 1))) ((= i 2000)) (irregex-match irx text))
        (quotient (- (sstats-bytes (statistics)) before) 2000)))
    (let ((baseline (allocated old)) (candidate (allocated new)))
      (printf "bytes/match baseline=~a candidate=~a\n" baseline candidate)
      (check "allocation oracle detects old closure construction" (> baseline 40000))
      (check "compiled repetition allocates under 8KiB/match" (< candidate 8192)))))
(printf "static-repeat ~a/~a checks passed\n" (- total failures) total)
(exit (if (= failures 0) 0 1))
