;; Source-runtime gate: fixed arities retain live :ops lookup and generic
;; larger-arity behavior. Allocation is a deterministic dispatch oracle, not
;; a throughput/tail claim. Run under the workspace's pinned Chez wrapper.
(import (chezscheme))
(load "host/chez/rt.ss")
(define total 0)
(define fails 0)
(define (ok name pred)
  (set! total (+ total 1))
  (unless pred (set! fails (+ fails 1)) (printf "FAIL: ~a\n" name)))
(define op (keyword #f "dispatch-test"))
(define table (jolt-tagged-table kw-sorted-map))
(define tag-table (jolt-tagged-table kw-sorted-map))
(ok "map tag recognized" (and (htable-sorted-map? tag-table) (not (htable-sorted-set? tag-table))))
(jolt-ref-put! tag-table (keyword "jolt" "type") kw-sorted-set)
(ok "tag replacement is live" (and (htable-sorted-set? tag-table) (not (htable-sorted-map? tag-table))))
(jolt-ref-put! tag-table (keyword "jolt" "type") jolt-nil)
(jolt-ref-put! tag-table (keyword "other" "type") kw-sorted-map)
(ok "removed or other-namespace tag is not sorted" (not (htable-sorted? tag-table)))
(ok "non-table is not sorted" (not (htable-sorted? empty-pmap)))
(jolt-ref-put! tag-table (keyword "jolt" "type") kw-sorted-map)
(define owner #f)
(jolt-ref-put! table kw-ops
  (jolt-hash-map op (lambda (sc . args) (set! owner sc) (apply jolt-vector args))))
(ok "zero op args" (= 0 (pvec-count (sc-call table op))))
(ok "one op arg" (= 7 (pvec-nth! (sc-call table op 7) 0)))
(ok "two op args" (jolt=2 (jolt-vector 7 8) (sc-call table op 7 8)))
(ok "three op args" (jolt=2 (jolt-vector 7 8 9) (sc-call table op 7 8 9)))
(ok "generic four op args" (jolt=2 (jolt-vector 7 8 9 10) (sc-call table op 7 8 9 10)))
(ok "exact receiver" (eq? owner table))
(jolt-ref-put! table kw-ops (jolt-hash-map op (jolt-hash-map table 17)))
(ok "non-procedure callable at one receiver arg" (= 17 (sc-call table op)))
(ok "non-procedure callable with default" (= 17 (sc-call table op 99)))
(ok "non-procedure callable rejects unsupported arity"
    (guard (e (#t #t)) (sc-call table op 7 8) #f))
(jolt-ref-put! table kw-ops (jolt-hash-map op (lambda (sc a b) (fx+ a b))))
(ok "operation replacement is live" (= 15 (sc-call table op 7 8)))
(ok "wrong arity is rejected"
    (guard (e (#t #t)) (sc-call table op 7) #f))
(jolt-ref-put! table kw-ops (jolt-hash-map op (lambda (sc a b) (error 'controlled "boom"))))
(ok "operation exception propagates"
    (guard (e (#t #t)) (sc-call table op 7 8) #f))
(jolt-ref-put! table kw-ops (jolt-hash-map op (lambda (sc a b) (fx+ a b))))
(define n 100000)
(define (bytes-per thunk)
  (thunk)
  (let ((before (sstats-bytes (statistics))))
    (do ((i 0 (fx+ i 1))) ((fx=? i n)) (thunk))
    (quotient (- (sstats-bytes (statistics)) before) n)))
(define positive (bytes-per (lambda () (make-vector 8 #f))))
(define dispatch (bytes-per (lambda () (sc-call table op 7 8))))
(define classification (bytes-per (lambda () (htable-sorted-map? tag-table))))
(printf "bytes/call: positive vector ~a, sorted dispatch ~a\n" positive dispatch)
(printf "bytes/call: sorted classification ~a\n" classification)
(ok "allocation counter observes fresh objects" (>= positive 64))
(ok "fixed sorted dispatch avoids argument lists" (<= dispatch 16))
(ok "fixed sorted classifier avoids field-name allocation" (<= classification 16))
(printf "sorted-op-dispatch: ~a/~a passed\n" (- total fails) total)
(exit (if (= fails 0) 0 1))
