(import (chezscheme))
(load "host/chez/rt.ss")
(define checks 0)
(define failures 0)
(define (ok label answer)
  (set! checks (+ checks 1))
  (unless answer (set! failures (+ failures 1)) (printf "FAIL ~a\n" label)))
(define (observe ids failed-id)
  (let ((old str-tostring-hook) (visits '()) (original (vector 'original-error))
        (caught #f) (result #f))
    (dynamic-wind
      (lambda ()
        (set! str-tostring-hook
          (lambda (x)
            (if (and (vector? x) (= (vector-length x) 2) (eq? (vector-ref x 0) 'fixture))
                (let ((id (vector-ref x 1)))
                  (set! visits (cons id visits))
                  (when (eq? id failed-id) (raise original))
                  (symbol->string id))
                (and old (old x))))))
      (lambda ()
        (set! result
          (guard (e (#t (set! caught e) #f))
            (apply jolt-str (map (lambda (id) (vector 'fixture id)) ids)))))
      (lambda () (set! str-tostring-hook old)))
    (list result (reverse visits) (and caught (eq? caught original)))))
(for-each
  (lambda (ids)
    (let ((observed (observe ids #f)))
      (ok "value remains in operand order"
          (string=? (car observed) (apply string-append (map symbol->string ids))))
      (ok "callbacks left-to-right" (equal? (cadr observed) ids))))
  '((a b) (a b c) (a b c d) (a b c d e)))
(for-each
  (lambda (ids)
    (let ((observed (observe ids 'b)))
      (ok "exception stops before later callbacks" (equal? (cadr observed) '(a b)))
      (ok "original exception identity" (caddr observed))))
  '((a b) (a b c) (a b c d e)))
(let ((s (string-copy "same")))
  (ok "single String identity" (eq? s (jolt-str s))))
(ok "ordinary values" (string=? (jolt-str jolt-nil "x" 3) "x3"))
(printf "str-render-order: ~a/~a checks passed\n" (- checks failures) checks)
(exit (if (= failures 0) 0 1))
