;; Deterministic materialization parity; no timing pass criterion.
(import (chezscheme))
(load "host/chez/rt.ss")
(define (check label actual expected)
  (unless (equal? actual expected)
    (error 'materialize label actual expected)))
(define (sink prefix) (make-jhost "writer" (vector prefix '() 0)))
(define pieces '#("" "a" "BC" "λ😀" "\n\"\\" "longer-piece"))
(for-each
 (lambda (size)
   (let ((writer (sink "base:λ")) (expected "base:λ"))
     (do ((i 0 (+ i 1))) ((= i size))
       (let ((piece (vector-ref pieces (modulo i (vector-length pieces)))))
         (sb-append! writer piece)
         (set! expected (string-append expected piece))))
     (let* ((state (jhost-state writer)) (pending (vector-ref state 1)))
       (check "non-flushing length" (sb-length writer) (string-length expected))
       (unless (eq? pending (vector-ref state 1))
         (error 'materialize "length changed pending chunks"))
       (let ((first (sb-str writer)))
         (check "ordered contents" first expected)
         (check "cleared chunks" (vector-ref state 1) '())
         (check "cleared pending length" (vector-ref state 2) 0)
         (unless (eq? first (sb-str writer))
           (error 'materialize "repeat read did not reuse materialization"))
         (sb-append! writer "tail😀")
         (check "append after read" (sb-str writer) (string-append expected "tail😀"))
         (check "retained prior read" first expected)
         (sb-set! writer "reset:")
         (sb-append! writer "x")
         (sb-append! writer "yz")
         (check "reset and asymmetric append" (sb-str writer) "reset:xyz")
         (check "retained read after reset" first expected)))))
 '(0 1 2 3 17 128 1024))
(let ((a (sink "A:")) (b (sink "B:")))
  (sb-append! a "1") (sb-append! b "22")
  (sb-append! a "333") (sb-append! b "4")
  (check "independent sink A" (sb-str a) "A:1333")
  (check "independent sink B" (sb-str b) "B:224"))
(display "string-builder-materialize: PASS\n")
