(import (chezscheme))
(load "host/chez/gate-boot.ss")
(define checks 0)
(define (check label value)
  (set! checks (fx+ checks 1))
  (unless value (error 'string-hash-cache label)))
(define samples
  (list "" "flag" "count" "Aa" "BB" "a\x0;b" "λ" "😀"
        (make-string 100000 #\x)))
(for-each
  (lambda (s)
    (check "exact cold hash" (= (string-hasheq s) (compute-string-hasheq s)))
    (check "exact warm hash" (= (string-hasheq s) (compute-string-hasheq s)))) samples)
;; Same boundaries/length guarantee a selector collision, not equal hashes.
(define a (string-copy "a000z"))
(define b (string-copy "a111z"))
(check "forced selector collision" (= (string-hasheq-cache-slot a) (string-hasheq-cache-slot b)))
(check "different actual hashes" (not (= (compute-string-hasheq a) (compute-string-hasheq b))))
(do ((i 0 (fx+ i 1))) ((fx=? i 1000))
  (check "eviction cannot return wrong hash" (= (string-hasheq a) (compute-string-hasheq a)))
  (check "collision cannot return wrong hash" (= (string-hasheq b) (compute-string-hasheq b))))
(define inputs (make-vector 10000 #f))
(do ((i 0 (fx+ i 1))) ((fx=? i 10000))
  (vector-set! inputs i (string-append "key-" (number->string i))))
(vector-for-each (lambda (s) (check "large working set" (= (string-hasheq s) (compute-string-hasheq s)))) inputs)
(collect)
(vector-for-each (lambda (s) (check "after GC" (= (string-hasheq s) (compute-string-hasheq s)))) inputs)
(check "fixed capacity" (= 4096 (vector-length (cdr (hasheq-caches)))))
;; Every native thread must start its own cache, not inherit the parent's slots.
(define parent-cache (cdr (hasheq-caches)))
(define caches (make-vector 4 #f))
(define failures (make-vector 4 #f))
(define mu (make-mutex))
(define cv (make-condition))
(define left 4)
(do ((i 0 (fx+ i 1))) ((fx=? i 4))
  (fork-thread
    (lambda ()
      (guard (e (#t (vector-set! failures i e)))
        (vector-set! caches i (cdr (hasheq-caches)))
        (do ((n 0 (fx+ n 1))) ((fx=? n 10000))
          (let ((s (vector-ref inputs n)))
            (unless (= (string-hasheq s) (compute-string-hasheq s))
              (error 'cache-thread "wrong hash")))))
      (with-mutex mu (set! left (fx- left 1)) (condition-broadcast cv)))))
(with-mutex mu (let wait () (unless (fx=? left 0) (condition-wait cv mu) (wait))))
(do ((i 0 (fx+ i 1))) ((fx=? i 4))
  (check "thread result" (not (vector-ref failures i)))
  (check "thread owns cache" (not (eq? parent-cache (vector-ref caches i))))
  (do ((j 0 (fx+ j 1))) ((fx=? j i))
    (check "distinct worker caches" (not (eq? (vector-ref caches i) (vector-ref caches j))))))
;; Allocation oracle rejects the previous entry-allocating cache, independently
;; of timing. Inputs already exist, and all cache storage is initialized.
(define old-table (make-eq-hashtable))
(define (old-cache s)
  (or (hashtable-ref old-table s #f)
      (let ((h (compute-string-hasheq s)))
        (when (fx>=? (hashtable-size old-table) 2048) (hashtable-clear! old-table))
        (hashtable-set! old-table s h) h)))
(define selected (if (getenv "JOLT_TEST_OLD_STRING_CACHE") old-cache string-hasheq))
(define (allocation-for f)
  (let ((before (sstats-bytes (statistics))))
    (do ((i 0 (fx+ i 1))) ((fx=? i 10000)) (f (vector-ref inputs i)))
    (- (sstats-bytes (statistics)) before)))
;; Source gates also pay cold hashtable-independent hashing costs. Compare
;; the identical invocation loop with uncached computation, not an assumed
;; zero-allocation absolute floor from a differently compiled runtime.
(define baseline (allocation-for compute-string-hasheq))
(define allocated (allocation-for selected))
(printf "Allocation diagnostic: uncached=~a selected=~a excess=~a bytes / 10k\n"
        baseline allocated (- allocated baseline))
(check "no per-miss cache entries" (< (- allocated baseline) 64000))
(printf "PASS string-hash cache: ~a checks\n" checks)
