(import (chezscheme))
(load "host/chez/rt.ss")
(define checks 0)
(define (check name condition)
  (set! checks (+ checks 1))
  (unless condition (error 'vector-constructor name)))
(define (reference xs) (make-pvec (list->vector xs)))
(for-each
  (lambda (n)
    (let* ((xs (map (lambda (i) (vector i)) (iota n)))
           (expected (reference xs))
           (actual (apply jolt-vector xs))
           (again (apply jolt-vector xs)))
      (check "count" (= (pvec-count actual) n))
      (check "fresh result" (not (eq? actual again)))
      (check "same kind" (eq? (pvec-ent expected) (pvec-ent actual)))
      (do ((i 0 (+ i 1))) ((= i n))
        (check "element identity" (eq? (pvec-nth! actual i) (list-ref xs i))))
      ;; Constructor never lends or mutates a caller's source list/backing.
      (when (> n 0)
        (set-car! xs 'changed)
        (check "source list independent" (not (eq? (pvec-nth! actual 0) 'changed))))))
  '(0 1 2 3 4 8 24 31 32 33 64 1025))
(let ((a (jolt-vector jolt-nil #f #t "λ")))
  (check "nil" (eq? (pvec-nth! a 0) jolt-nil))
  (check "false" (eq? (pvec-nth! a 1) #f))
  (check "true" (eq? (pvec-nth! a 2) #t))
  (check "unicode" (string=? (pvec-nth! a 3) "λ")))
(printf "vector constructor: ~a checks passed\n" checks)

;; Non-vacuous allocation control: both paths construct exactly the same
;; two-element persistent vector, but the old path must create a rest list.
;; Chez cumulative statistics count allocations even when collection occurs.
(define (old-constructor . xs) (make-pvec (list->vector xs)))
(define (allocated f)
  (collect)
  (let ((before (sstats-bytes (statistics))))
    (do ((i 0 (+ i 1))) ((= i 100000)) (f i #f))
    (- (sstats-bytes (statistics)) before)))
(define old-bytes (allocated old-constructor))
(when (equal? (getenv "JOLT_TEST_OLD_VECTOR_CONSTRUCTOR") "1")
  ;; Local red control: the allocation gate must reject the previous body.
  (set! jolt-vector old-constructor))
(define new-bytes (allocated jolt-vector))
(check "rest-list allocation removed" (< new-bytes (* old-bytes 0.95)))
(printf "two-element constructor allocation: old ~a new ~a bytes\n" old-bytes new-bytes)
